name: main

on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    # Install node
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # Install Yarn
    - name: Install Yarn
      run: npm i -g yarn
    # Yarn caches
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v1
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    # Install dependencies
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Build
      run: yarn run build
    - name: Test
      run: yarn run test
    - name: Coverage
      run: yarn run coverage
    - name: Upload bundles
      uses: actions/upload-artifact@v2
      with:
        name: lib
        path: |
          esm
          cjs
          lib
          preview
    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage

